// Code generated by generate/merge.go; DO NOT EDIT.

package discord
func(dst *Guild) Merge(source *Guild) {
    if source.Name != "" {
        dst.Name = source.Name
    }
    if source.Icon != "" {
        dst.Icon = source.Icon
    }
    if source.Splash != "" {
        dst.Splash = source.Splash
    }
    if source.OwnerID != 0 {
        dst.OwnerID = source.OwnerID
    }
    if source.Region != "" {
        dst.Region = source.Region
    }
    if source.AfkChannelID != 0 {
        dst.AfkChannelID = source.AfkChannelID
    }
    if source.AfkTimeout != 0 {
        dst.AfkTimeout = source.AfkTimeout
    }
    if source.VerificationLevel != 0 {
        dst.VerificationLevel = source.VerificationLevel
    }
    if source.DefaultMessageNotifications != 0 {
        dst.DefaultMessageNotifications = source.DefaultMessageNotifications
    }
    if source.ExplicitContentFilter != 0 {
        dst.ExplicitContentFilter = source.ExplicitContentFilter
    }
    if source.Emojis != nil {
        dst.Emojis = source.Emojis
    }
    if source.Features != nil {
        dst.Features = source.Features
    }
    if source.MFALevel != 0 {
        dst.MFALevel = source.MFALevel
    }
    if source.WidgetEnabled != false {
        dst.WidgetEnabled = source.WidgetEnabled
    }
    if source.WidgetChannelID != 0 {
        dst.WidgetChannelID = source.WidgetChannelID
    }
    if source.SystemChannelID != 0 {
        dst.SystemChannelID = source.SystemChannelID
    }
    if source.DiscoverySplash != "" {
        dst.DiscoverySplash = source.DiscoverySplash
    }
    if source.VanityUrl != "" {
        dst.VanityUrl = source.VanityUrl
    }
    if source.Description != "" {
        dst.Description = source.Description
    }
    if source.Banner != "" {
        dst.Banner = source.Banner
    }
    if source.PremiumTier != 0 {
        dst.PremiumTier = source.PremiumTier
    }
    if source.PremiumSubscriptionCount != 0 {
        dst.PremiumSubscriptionCount = source.PremiumSubscriptionCount
    }
    if source.MaxPresences != 0 {
        dst.MaxPresences = source.MaxPresences
    }
    if source.MaxMembers != 0 {
        dst.MaxMembers = source.MaxMembers
    }
    if source.PublicUpdatesChannel != 0 {
        dst.PublicUpdatesChannel = source.PublicUpdatesChannel
    }
    if source.RulesChannel != 0 {
        dst.RulesChannel = source.RulesChannel
    }
    if source.JoinedAt != nil {
        dst.JoinedAt = source.JoinedAt
    }
    if source.Large != false {
        dst.Large = source.Large
    }
    if source.Unavailable != false {
        dst.Unavailable = source.Unavailable
    }
}
